# Generated by Django 2.0.4 on 2018-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('book_ISBN', models.CharField(max_length=50)),
                ('pub_date', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
